AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  6998HW2LF1:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./LambdaCode/lambda_function.py
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::207598852675:role/service-role/6998HW2_LF1-role-vwcil9ea'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /upload
            Method: PUT

